name: building_manager
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+2

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_switch: ^0.3.2
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  flutter_screenutil: ^5.0.0+2
  sprintf: ^6.0.0
  kiwi: ^3.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_svg: ^0.22.0
  dio: ^4.0.0
  connectivity: ^3.0.6
  shared_preferences: ^2.0.6
  cached_network_image: ^3.1.0
  fluttertoast: ^8.0.8
  photo_view: ^0.13.0
  built_value: ^8.1.4
  flutter_html: ^2.2.1
  google_sign_in: ^5.0.7
  #sign_in_with_apple: ^3.0.0
  floor: ^1.1.0
  image_picker: ^0.8.6
  image: ^3.0.2
  flutter_native_image: ^0.0.6
  syncfusion_flutter_calendar: ^19.4.54
  #  rxdart: ^0.27.2
  #  flutter_phone_direct_caller: ^2.1.1
  #  confetti: ^0.6.0
  firebase_core: any
  firebase_messaging: any
  flutter_local_notifications: any
  permission_handler: ^10.2.0
  #  firebase_messaging_platform_interface: 3.1.6
  #  firebase_analytics: ^9.1.1
  device_info_plus: ^3.0.1
  flutter_tags: 1.0.0-nullsafety.1
  syncfusion_flutter_charts: ^19.1.54
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^2.0.4
  flutter_slidable: ^1.2.1
  flutter_share: ^2.0.0
  flutter_colorpicker: ^1.0.3
  sentry_flutter: ^6.6.1
  sentry_dio: ^6.6.3
  get: any
  get_storage: ^2.0.3
  #  im_stepper: ^0.1.3
  #  flutter_sound: ^9.2.13
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  # play videos
  video_player: ^2.4.7
  flutter_sound: ^9.2.13
  audio_session: ^0.1.10
  just_audio: ^0.9.30
  substring_highlight: ^1.0.33
  dotted_border: ^2.0.0
  #  flutter_vlc_player: ^7.1.5

  #  assets_audio_player: ^3.0.3+3

  camera: ^0.10.0+1
  path: ^1.8.0
  path_provider: ^2.0.2
  gallery_saver: ^2.3.2
  intl: ^0.17.0



  #  open_file: ^3.2.1
  #  path_provider: ^2.0.2
  #  printing: ^5.3.0
  #  url_launcher: ^6.0.6
  #  permission_handler: ^8.1.6
  #  contacts_service: ^0.6.3
  #  syncfusion_flutter_signaturepad: ^19.3.47
  file_picker: ^4.2.7
  #  in_app_purchase: ^2.0.1

  # plugin api
  openapi:
    #    git: https://git.toprate.io/an-phu/plugin-api.git
    path: ./api


  #  table_calendar:
  #    path: ./table_calendar
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.0.6
  built_value_generator: any
  kiwi_generator: ^3.0.0
  floor_generator: ^1.1.0
  flutter_test:
    sdk: flutter

## Local Dev only
dependency_overrides:
#  analyzer: 4.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/languages/

  #font
  fonts:

    #    - family: Montserrat
    #      fonts:
    #        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
    #        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
    #        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
    #        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
    #        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
    #        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
    #
    #    - family: Roboto
    #      fonts:
    #        - asset: assets/fonts/roboto/Roboto-Regular.ttf
    #        - asset: assets/fonts/roboto/Roboto-Medium.ttf
    #        - asset: assets/fonts/roboto/Roboto-Bold.ttf
    #    - family: Lato
    #      fonts:
    #        - asset: assets/fonts/lato/Lato-Bold.ttf
    #        - asset: assets/fonts/lato/Lato-Regular.ttf

    #    - family: Srisakdi
    #      fonts:
    #        - asset: assets/fonts/srisakdi/Srisakdi-Bold.ttf
    #        - asset: assets/fonts/srisakdi/Srisakdi-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf

#    - family: Rubik
#      fonts:
#        - asset: assets/fonts/rubik/Rubik-Bold.ttf
#        - asset: assets/fonts/rubik/Rubik-Italic.ttf
#        - asset: assets/fonts/rubik/Rubik-Medium.ttf
#        - asset: assets/fonts/rubik/Rubik-Regular.ttf



